// flow-typed signature: 055df31f2b29df93b4e0f40055973511
// flow-typed version: <<STUB>>/@microsoft/microsoft-graph-client_v^1.3.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@microsoft/microsoft-graph-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@microsoft/microsoft-graph-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@microsoft/microsoft-graph-client/lib/es/browser' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/browser/MSALAuthenticationProvider' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/Client' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/Constants' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/content/BatchRequestContent' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/content/BatchResponseContent' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/CustomAuthenticationProvider' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/GraphError' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/GraphErrorHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/GraphRequest' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/GraphRequestUtil' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/GraphResponseHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/HTTPClient' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/HTTPClientFactory' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/IAuthenticationProvider' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/IAuthenticationProviderOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/IAuthProvider' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/IAuthProviderCallback' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/IClientOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/IContext' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/IFetchOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/IGraphRequestCallback' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/IOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/AuthenticationHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/HTTPMessageHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/IMiddleware' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/MiddlewareControl' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/MiddlewareUtil' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/options/AuthenticationHandlerOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/options/IMiddlewareOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/options/RedirectHandlerOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/options/RetryHandlerOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/options/TelemetryHandlerOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/RedirectHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/RetryHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/middleware/TelemetryHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/MSALAuthenticationProvider' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/MSALAuthenticationProviderOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/PolyFill' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/Range' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/RequestMethod' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/ResponseType' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/tasks/LargeFileUploadTask' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/tasks/OneDriveLargeFileUploadTask' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/tasks/OneDriveLargeFileUploadTaskUtil' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/tasks/PageIterator' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/es/ValidatePolyFilling' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/graph-es-sdk' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/graph-js-sdk-core' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/graph-js-sdk-web' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/browser' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/browser/MSALAuthenticationProvider' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/Client' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/Constants' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/content/BatchRequestContent' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/content/BatchResponseContent' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/CustomAuthenticationProvider' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/GraphError' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/GraphRequest' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/GraphRequestUtil' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/GraphResponseHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/HTTPClient' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/HTTPClientFactory' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/IAuthenticationProvider' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/IAuthenticationProviderOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/IAuthProvider' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/IAuthProviderCallback' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/IClientOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/IContext' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/IFetchOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/IGraphRequestCallback' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/IOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/AuthenticationHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/HTTPMessageHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/IMiddleware' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/MiddlewareControl' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/MiddlewareUtil' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/options/AuthenticationHandlerOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/options/IMiddlewareOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/options/RedirectHandlerOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/options/RetryHandlerOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/options/TelemetryHandlerOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/RedirectHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/RetryHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/middleware/TelemetryHandler' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/MSALAuthenticationProvider' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/MSALAuthenticationProviderOptions' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/PolyFill' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/Range' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/RequestMethod' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/ResponseType' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/tasks/LargeFileUploadTask' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/tasks/OneDriveLargeFileUploadTask' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/tasks/OneDriveLargeFileUploadTaskUtil' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/tasks/PageIterator' {
  declare module.exports: any;
}

declare module '@microsoft/microsoft-graph-client/lib/src/ValidatePolyFilling' {
  declare module.exports: any;
}

// Filename aliases
declare module '@microsoft/microsoft-graph-client/lib/es/browser/index' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/browser'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/browser/index.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/browser'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/browser/MSALAuthenticationProvider.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/browser/MSALAuthenticationProvider'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/Client.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/Client'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/Constants.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/Constants'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/content/BatchRequestContent.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/content/BatchRequestContent'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/content/BatchResponseContent.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/content/BatchResponseContent'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/CustomAuthenticationProvider.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/CustomAuthenticationProvider'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/GraphError.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/GraphError'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/GraphErrorHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/GraphErrorHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/GraphRequest.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/GraphRequest'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/GraphRequestUtil.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/GraphRequestUtil'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/GraphResponseHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/GraphResponseHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/HTTPClient.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/HTTPClient'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/HTTPClientFactory.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/HTTPClientFactory'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/IAuthenticationProvider.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/IAuthenticationProvider'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/IAuthenticationProviderOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/IAuthenticationProviderOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/IAuthProvider.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/IAuthProvider'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/IAuthProviderCallback.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/IAuthProviderCallback'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/IClientOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/IClientOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/IContext.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/IContext'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/IFetchOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/IFetchOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/IGraphRequestCallback.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/IGraphRequestCallback'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/index' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/index.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/IOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/IOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/AuthenticationHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/AuthenticationHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/HTTPMessageHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/HTTPMessageHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/IMiddleware.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/IMiddleware'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/MiddlewareControl.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/MiddlewareControl'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/MiddlewareUtil.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/MiddlewareUtil'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/options/AuthenticationHandlerOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/options/AuthenticationHandlerOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/options/IMiddlewareOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/options/IMiddlewareOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/options/RedirectHandlerOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/options/RedirectHandlerOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/options/RetryHandlerOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/options/RetryHandlerOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/options/TelemetryHandlerOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/options/TelemetryHandlerOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/RedirectHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/RedirectHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/RetryHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/RetryHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/middleware/TelemetryHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/middleware/TelemetryHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/MSALAuthenticationProvider.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/MSALAuthenticationProvider'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/MSALAuthenticationProviderOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/MSALAuthenticationProviderOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/PolyFill.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/PolyFill'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/Range.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/Range'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/RequestMethod.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/RequestMethod'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/ResponseType.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/ResponseType'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/tasks/LargeFileUploadTask.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/tasks/LargeFileUploadTask'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/tasks/OneDriveLargeFileUploadTask.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/tasks/OneDriveLargeFileUploadTask'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/tasks/OneDriveLargeFileUploadTaskUtil.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/tasks/OneDriveLargeFileUploadTaskUtil'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/tasks/PageIterator.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/tasks/PageIterator'>;
}
declare module '@microsoft/microsoft-graph-client/lib/es/ValidatePolyFilling.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/es/ValidatePolyFilling'>;
}
declare module '@microsoft/microsoft-graph-client/lib/graph-es-sdk.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/graph-es-sdk'>;
}
declare module '@microsoft/microsoft-graph-client/lib/graph-js-sdk-core.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/graph-js-sdk-core'>;
}
declare module '@microsoft/microsoft-graph-client/lib/graph-js-sdk-web.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/graph-js-sdk-web'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/browser/index' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/browser'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/browser/index.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/browser'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/browser/MSALAuthenticationProvider.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/browser/MSALAuthenticationProvider'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/Client.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/Client'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/Constants.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/Constants'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/content/BatchRequestContent.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/content/BatchRequestContent'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/content/BatchResponseContent.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/content/BatchResponseContent'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/CustomAuthenticationProvider.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/CustomAuthenticationProvider'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/GraphError.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/GraphError'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/GraphRequest.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/GraphRequest'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/GraphRequestUtil.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/GraphRequestUtil'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/GraphResponseHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/GraphResponseHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/HTTPClient.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/HTTPClient'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/HTTPClientFactory.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/HTTPClientFactory'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/IAuthenticationProvider.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/IAuthenticationProvider'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/IAuthenticationProviderOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/IAuthenticationProviderOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/IAuthProvider.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/IAuthProvider'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/IAuthProviderCallback.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/IAuthProviderCallback'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/IClientOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/IClientOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/IContext.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/IContext'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/IFetchOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/IFetchOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/IGraphRequestCallback.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/IGraphRequestCallback'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/index' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/index.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/IOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/IOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/AuthenticationHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/AuthenticationHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/HTTPMessageHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/HTTPMessageHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/IMiddleware.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/IMiddleware'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/MiddlewareControl.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/MiddlewareControl'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/MiddlewareUtil.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/MiddlewareUtil'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/options/AuthenticationHandlerOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/options/AuthenticationHandlerOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/options/IMiddlewareOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/options/IMiddlewareOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/options/RedirectHandlerOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/options/RedirectHandlerOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/options/RetryHandlerOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/options/RetryHandlerOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/options/TelemetryHandlerOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/options/TelemetryHandlerOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/RedirectHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/RedirectHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/RetryHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/RetryHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/middleware/TelemetryHandler.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/middleware/TelemetryHandler'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/MSALAuthenticationProvider.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/MSALAuthenticationProvider'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/MSALAuthenticationProviderOptions.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/MSALAuthenticationProviderOptions'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/PolyFill.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/PolyFill'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/Range.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/Range'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/RequestMethod.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/RequestMethod'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/ResponseType.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/ResponseType'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/tasks/LargeFileUploadTask.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/tasks/LargeFileUploadTask'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/tasks/OneDriveLargeFileUploadTask.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/tasks/OneDriveLargeFileUploadTask'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/tasks/OneDriveLargeFileUploadTaskUtil.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/tasks/OneDriveLargeFileUploadTaskUtil'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/tasks/PageIterator.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/tasks/PageIterator'>;
}
declare module '@microsoft/microsoft-graph-client/lib/src/ValidatePolyFilling.js' {
  declare module.exports: $Exports<'@microsoft/microsoft-graph-client/lib/src/ValidatePolyFilling'>;
}
