// flow-typed signature: 62fa4a58df18a46387e5e3d5a1a20ef9
// flow-typed version: <<STUB>>/dav_v^1.8.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dav'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dav' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dav/build/accounts' {
  declare module.exports: any;
}

declare module 'dav/build/calendars' {
  declare module.exports: any;
}

declare module 'dav/build/camelize' {
  declare module.exports: any;
}

declare module 'dav/build/client' {
  declare module.exports: any;
}

declare module 'dav/build/contacts' {
  declare module.exports: any;
}

declare module 'dav/build/debug' {
  declare module.exports: any;
}

declare module 'dav/build/fuzzy_url_equals' {
  declare module.exports: any;
}

declare module 'dav/build' {
  declare module.exports: any;
}

declare module 'dav/build/model' {
  declare module.exports: any;
}

declare module 'dav/build/namespace' {
  declare module.exports: any;
}

declare module 'dav/build/parser' {
  declare module.exports: any;
}

declare module 'dav/build/polyfill/array_find' {
  declare module.exports: any;
}

declare module 'dav/build/polyfill/object_assign' {
  declare module.exports: any;
}

declare module 'dav/build/polyfill/regenerator_runtime' {
  declare module.exports: any;
}

declare module 'dav/build/request' {
  declare module.exports: any;
}

declare module 'dav/build/sandbox' {
  declare module.exports: any;
}

declare module 'dav/build/template/address_book_query' {
  declare module.exports: any;
}

declare module 'dav/build/template/calendar_query' {
  declare module.exports: any;
}

declare module 'dav/build/template/filter' {
  declare module.exports: any;
}

declare module 'dav/build/template' {
  declare module.exports: any;
}

declare module 'dav/build/template/prop' {
  declare module.exports: any;
}

declare module 'dav/build/template/propfind' {
  declare module.exports: any;
}

declare module 'dav/build/template/sync_collection' {
  declare module.exports: any;
}

declare module 'dav/build/transport' {
  declare module.exports: any;
}

declare module 'dav/build/webdav' {
  declare module.exports: any;
}

declare module 'dav/build/xmlhttprequest' {
  declare module.exports: any;
}

declare module 'dav/dav' {
  declare module.exports: any;
}

declare module 'dav/dav.min' {
  declare module.exports: any;
}

declare module 'dav/lib/accounts' {
  declare module.exports: any;
}

declare module 'dav/lib/calendars' {
  declare module.exports: any;
}

declare module 'dav/lib/camelize' {
  declare module.exports: any;
}

declare module 'dav/lib/client' {
  declare module.exports: any;
}

declare module 'dav/lib/contacts' {
  declare module.exports: any;
}

declare module 'dav/lib/debug' {
  declare module.exports: any;
}

declare module 'dav/lib/fuzzy_url_equals' {
  declare module.exports: any;
}

declare module 'dav/lib' {
  declare module.exports: any;
}

declare module 'dav/lib/model' {
  declare module.exports: any;
}

declare module 'dav/lib/namespace' {
  declare module.exports: any;
}

declare module 'dav/lib/parser' {
  declare module.exports: any;
}

declare module 'dav/lib/polyfill/array_find' {
  declare module.exports: any;
}

declare module 'dav/lib/polyfill/object_assign' {
  declare module.exports: any;
}

declare module 'dav/lib/polyfill/regenerator_runtime' {
  declare module.exports: any;
}

declare module 'dav/lib/request' {
  declare module.exports: any;
}

declare module 'dav/lib/sandbox' {
  declare module.exports: any;
}

declare module 'dav/lib/template/address_book_query' {
  declare module.exports: any;
}

declare module 'dav/lib/template/calendar_query' {
  declare module.exports: any;
}

declare module 'dav/lib/template/filter' {
  declare module.exports: any;
}

declare module 'dav/lib/template' {
  declare module.exports: any;
}

declare module 'dav/lib/template/prop' {
  declare module.exports: any;
}

declare module 'dav/lib/template/propfind' {
  declare module.exports: any;
}

declare module 'dav/lib/template/sync_collection' {
  declare module.exports: any;
}

declare module 'dav/lib/transport' {
  declare module.exports: any;
}

declare module 'dav/lib/webdav' {
  declare module.exports: any;
}

declare module 'dav/lib/xmlhttprequest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dav/build/accounts.js' {
  declare module.exports: $Exports<'dav/build/accounts'>;
}
declare module 'dav/build/calendars.js' {
  declare module.exports: $Exports<'dav/build/calendars'>;
}
declare module 'dav/build/camelize.js' {
  declare module.exports: $Exports<'dav/build/camelize'>;
}
declare module 'dav/build/client.js' {
  declare module.exports: $Exports<'dav/build/client'>;
}
declare module 'dav/build/contacts.js' {
  declare module.exports: $Exports<'dav/build/contacts'>;
}
declare module 'dav/build/debug.js' {
  declare module.exports: $Exports<'dav/build/debug'>;
}
declare module 'dav/build/fuzzy_url_equals.js' {
  declare module.exports: $Exports<'dav/build/fuzzy_url_equals'>;
}
declare module 'dav/build/index' {
  declare module.exports: $Exports<'dav/build'>;
}
declare module 'dav/build/index.js' {
  declare module.exports: $Exports<'dav/build'>;
}
declare module 'dav/build/model.js' {
  declare module.exports: $Exports<'dav/build/model'>;
}
declare module 'dav/build/namespace.js' {
  declare module.exports: $Exports<'dav/build/namespace'>;
}
declare module 'dav/build/parser.js' {
  declare module.exports: $Exports<'dav/build/parser'>;
}
declare module 'dav/build/polyfill/array_find.js' {
  declare module.exports: $Exports<'dav/build/polyfill/array_find'>;
}
declare module 'dav/build/polyfill/object_assign.js' {
  declare module.exports: $Exports<'dav/build/polyfill/object_assign'>;
}
declare module 'dav/build/polyfill/regenerator_runtime.js' {
  declare module.exports: $Exports<'dav/build/polyfill/regenerator_runtime'>;
}
declare module 'dav/build/request.js' {
  declare module.exports: $Exports<'dav/build/request'>;
}
declare module 'dav/build/sandbox.js' {
  declare module.exports: $Exports<'dav/build/sandbox'>;
}
declare module 'dav/build/template/address_book_query.js' {
  declare module.exports: $Exports<'dav/build/template/address_book_query'>;
}
declare module 'dav/build/template/calendar_query.js' {
  declare module.exports: $Exports<'dav/build/template/calendar_query'>;
}
declare module 'dav/build/template/filter.js' {
  declare module.exports: $Exports<'dav/build/template/filter'>;
}
declare module 'dav/build/template/index' {
  declare module.exports: $Exports<'dav/build/template'>;
}
declare module 'dav/build/template/index.js' {
  declare module.exports: $Exports<'dav/build/template'>;
}
declare module 'dav/build/template/prop.js' {
  declare module.exports: $Exports<'dav/build/template/prop'>;
}
declare module 'dav/build/template/propfind.js' {
  declare module.exports: $Exports<'dav/build/template/propfind'>;
}
declare module 'dav/build/template/sync_collection.js' {
  declare module.exports: $Exports<'dav/build/template/sync_collection'>;
}
declare module 'dav/build/transport.js' {
  declare module.exports: $Exports<'dav/build/transport'>;
}
declare module 'dav/build/webdav.js' {
  declare module.exports: $Exports<'dav/build/webdav'>;
}
declare module 'dav/build/xmlhttprequest.js' {
  declare module.exports: $Exports<'dav/build/xmlhttprequest'>;
}
declare module 'dav/dav.js' {
  declare module.exports: $Exports<'dav/dav'>;
}
declare module 'dav/dav.min.js' {
  declare module.exports: $Exports<'dav/dav.min'>;
}
declare module 'dav/lib/accounts.js' {
  declare module.exports: $Exports<'dav/lib/accounts'>;
}
declare module 'dav/lib/calendars.js' {
  declare module.exports: $Exports<'dav/lib/calendars'>;
}
declare module 'dav/lib/camelize.js' {
  declare module.exports: $Exports<'dav/lib/camelize'>;
}
declare module 'dav/lib/client.js' {
  declare module.exports: $Exports<'dav/lib/client'>;
}
declare module 'dav/lib/contacts.js' {
  declare module.exports: $Exports<'dav/lib/contacts'>;
}
declare module 'dav/lib/debug.js' {
  declare module.exports: $Exports<'dav/lib/debug'>;
}
declare module 'dav/lib/fuzzy_url_equals.js' {
  declare module.exports: $Exports<'dav/lib/fuzzy_url_equals'>;
}
declare module 'dav/lib/index' {
  declare module.exports: $Exports<'dav/lib'>;
}
declare module 'dav/lib/index.js' {
  declare module.exports: $Exports<'dav/lib'>;
}
declare module 'dav/lib/model.js' {
  declare module.exports: $Exports<'dav/lib/model'>;
}
declare module 'dav/lib/namespace.js' {
  declare module.exports: $Exports<'dav/lib/namespace'>;
}
declare module 'dav/lib/parser.js' {
  declare module.exports: $Exports<'dav/lib/parser'>;
}
declare module 'dav/lib/polyfill/array_find.js' {
  declare module.exports: $Exports<'dav/lib/polyfill/array_find'>;
}
declare module 'dav/lib/polyfill/object_assign.js' {
  declare module.exports: $Exports<'dav/lib/polyfill/object_assign'>;
}
declare module 'dav/lib/polyfill/regenerator_runtime.js' {
  declare module.exports: $Exports<'dav/lib/polyfill/regenerator_runtime'>;
}
declare module 'dav/lib/request.js' {
  declare module.exports: $Exports<'dav/lib/request'>;
}
declare module 'dav/lib/sandbox.js' {
  declare module.exports: $Exports<'dav/lib/sandbox'>;
}
declare module 'dav/lib/template/address_book_query.js' {
  declare module.exports: $Exports<'dav/lib/template/address_book_query'>;
}
declare module 'dav/lib/template/calendar_query.js' {
  declare module.exports: $Exports<'dav/lib/template/calendar_query'>;
}
declare module 'dav/lib/template/filter.js' {
  declare module.exports: $Exports<'dav/lib/template/filter'>;
}
declare module 'dav/lib/template/index' {
  declare module.exports: $Exports<'dav/lib/template'>;
}
declare module 'dav/lib/template/index.js' {
  declare module.exports: $Exports<'dav/lib/template'>;
}
declare module 'dav/lib/template/prop.js' {
  declare module.exports: $Exports<'dav/lib/template/prop'>;
}
declare module 'dav/lib/template/propfind.js' {
  declare module.exports: $Exports<'dav/lib/template/propfind'>;
}
declare module 'dav/lib/template/sync_collection.js' {
  declare module.exports: $Exports<'dav/lib/template/sync_collection'>;
}
declare module 'dav/lib/transport.js' {
  declare module.exports: $Exports<'dav/lib/transport'>;
}
declare module 'dav/lib/webdav.js' {
  declare module.exports: $Exports<'dav/lib/webdav'>;
}
declare module 'dav/lib/xmlhttprequest.js' {
  declare module.exports: $Exports<'dav/lib/xmlhttprequest'>;
}
