// flow-typed signature: 8e164270c79d021ec3a39c1ea8e55962
// flow-typed version: <<STUB>>/ical-toolkit_v^1.0.9/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ical-toolkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ical-toolkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ical-toolkit/lib/builder' {
  declare module.exports: any;
}

declare module 'ical-toolkit/lib/main' {
  declare module.exports: any;
}

declare module 'ical-toolkit/lib/parser' {
  declare module.exports: any;
}

declare module 'ical-toolkit/tests/parser' {
  declare module.exports: any;
}

declare module 'ical-toolkit/tests/test' {
  declare module.exports: any;
}

declare module 'ical-toolkit/timezones/_parse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ical-toolkit/lib/builder.js' {
  declare module.exports: $Exports<'ical-toolkit/lib/builder'>;
}
declare module 'ical-toolkit/lib/main.js' {
  declare module.exports: $Exports<'ical-toolkit/lib/main'>;
}
declare module 'ical-toolkit/lib/parser.js' {
  declare module.exports: $Exports<'ical-toolkit/lib/parser'>;
}
declare module 'ical-toolkit/tests/parser.js' {
  declare module.exports: $Exports<'ical-toolkit/tests/parser'>;
}
declare module 'ical-toolkit/tests/test.js' {
  declare module.exports: $Exports<'ical-toolkit/tests/test'>;
}
declare module 'ical-toolkit/timezones/_parse.js' {
  declare module.exports: $Exports<'ical-toolkit/timezones/_parse'>;
}
