// flow-typed signature: f2b4440345fa44d9e5a714ba73cea826
// flow-typed version: <<STUB>>/msal_v^0.2.4/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'msal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'msal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'msal/dist/msal' {
  declare module.exports: any;
}

declare module 'msal/dist/msal.min' {
  declare module.exports: any;
}

declare module 'msal/docs/assets/js/main' {
  declare module.exports: any;
}

declare module 'msal/docs/assets/js/search' {
  declare module.exports: any;
}

declare module 'msal/Gruntfile' {
  declare module.exports: any;
}

declare module 'msal/karma.conf' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/AadAuthority' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/AccessTokenCacheItem' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/AccessTokenKey' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/AccessTokenValue' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/AuthenticationRequestParameters' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/Authority' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/AuthorityFactory' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/B2cAuthority' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/ClientInfo' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/Constants' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/ErrorMessage' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/IdToken' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/ITenantDiscoveryResponse' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/IUri' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/Logger' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/RequestInfo' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/Storage' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/User' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/UserAgentApplication' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/Utils' {
  declare module.exports: any;
}

declare module 'msal/lib-commonjs/XHRClient' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/AadAuthority' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/AccessTokenCacheItem' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/AccessTokenKey' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/AccessTokenValue' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/AuthenticationRequestParameters' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/Authority' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/AuthorityFactory' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/B2cAuthority' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/ClientInfo' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/Constants' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/ErrorMessage' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/IdToken' {
  declare module.exports: any;
}

declare module 'msal/lib-es6' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/ITenantDiscoveryResponse' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/IUri' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/Logger' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/RequestInfo' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/Storage' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/User' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/UserAgentApplication' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/Utils' {
  declare module.exports: any;
}

declare module 'msal/lib-es6/XHRClient' {
  declare module.exports: any;
}

declare module 'msal/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'msal/dist/msal.js' {
  declare module.exports: $Exports<'msal/dist/msal'>;
}
declare module 'msal/dist/msal.min.js' {
  declare module.exports: $Exports<'msal/dist/msal.min'>;
}
declare module 'msal/docs/assets/js/main.js' {
  declare module.exports: $Exports<'msal/docs/assets/js/main'>;
}
declare module 'msal/docs/assets/js/search.js' {
  declare module.exports: $Exports<'msal/docs/assets/js/search'>;
}
declare module 'msal/Gruntfile.js' {
  declare module.exports: $Exports<'msal/Gruntfile'>;
}
declare module 'msal/karma.conf.js' {
  declare module.exports: $Exports<'msal/karma.conf'>;
}
declare module 'msal/lib-commonjs/AadAuthority.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/AadAuthority'>;
}
declare module 'msal/lib-commonjs/AccessTokenCacheItem.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/AccessTokenCacheItem'>;
}
declare module 'msal/lib-commonjs/AccessTokenKey.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/AccessTokenKey'>;
}
declare module 'msal/lib-commonjs/AccessTokenValue.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/AccessTokenValue'>;
}
declare module 'msal/lib-commonjs/AuthenticationRequestParameters.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/AuthenticationRequestParameters'>;
}
declare module 'msal/lib-commonjs/Authority.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/Authority'>;
}
declare module 'msal/lib-commonjs/AuthorityFactory.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/AuthorityFactory'>;
}
declare module 'msal/lib-commonjs/B2cAuthority.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/B2cAuthority'>;
}
declare module 'msal/lib-commonjs/ClientInfo.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/ClientInfo'>;
}
declare module 'msal/lib-commonjs/Constants.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/Constants'>;
}
declare module 'msal/lib-commonjs/ErrorMessage.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/ErrorMessage'>;
}
declare module 'msal/lib-commonjs/IdToken.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/IdToken'>;
}
declare module 'msal/lib-commonjs/index' {
  declare module.exports: $Exports<'msal/lib-commonjs'>;
}
declare module 'msal/lib-commonjs/index.js' {
  declare module.exports: $Exports<'msal/lib-commonjs'>;
}
declare module 'msal/lib-commonjs/ITenantDiscoveryResponse.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/ITenantDiscoveryResponse'>;
}
declare module 'msal/lib-commonjs/IUri.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/IUri'>;
}
declare module 'msal/lib-commonjs/Logger.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/Logger'>;
}
declare module 'msal/lib-commonjs/RequestInfo.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/RequestInfo'>;
}
declare module 'msal/lib-commonjs/Storage.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/Storage'>;
}
declare module 'msal/lib-commonjs/User.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/User'>;
}
declare module 'msal/lib-commonjs/UserAgentApplication.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/UserAgentApplication'>;
}
declare module 'msal/lib-commonjs/Utils.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/Utils'>;
}
declare module 'msal/lib-commonjs/XHRClient.js' {
  declare module.exports: $Exports<'msal/lib-commonjs/XHRClient'>;
}
declare module 'msal/lib-es6/AadAuthority.js' {
  declare module.exports: $Exports<'msal/lib-es6/AadAuthority'>;
}
declare module 'msal/lib-es6/AccessTokenCacheItem.js' {
  declare module.exports: $Exports<'msal/lib-es6/AccessTokenCacheItem'>;
}
declare module 'msal/lib-es6/AccessTokenKey.js' {
  declare module.exports: $Exports<'msal/lib-es6/AccessTokenKey'>;
}
declare module 'msal/lib-es6/AccessTokenValue.js' {
  declare module.exports: $Exports<'msal/lib-es6/AccessTokenValue'>;
}
declare module 'msal/lib-es6/AuthenticationRequestParameters.js' {
  declare module.exports: $Exports<'msal/lib-es6/AuthenticationRequestParameters'>;
}
declare module 'msal/lib-es6/Authority.js' {
  declare module.exports: $Exports<'msal/lib-es6/Authority'>;
}
declare module 'msal/lib-es6/AuthorityFactory.js' {
  declare module.exports: $Exports<'msal/lib-es6/AuthorityFactory'>;
}
declare module 'msal/lib-es6/B2cAuthority.js' {
  declare module.exports: $Exports<'msal/lib-es6/B2cAuthority'>;
}
declare module 'msal/lib-es6/ClientInfo.js' {
  declare module.exports: $Exports<'msal/lib-es6/ClientInfo'>;
}
declare module 'msal/lib-es6/Constants.js' {
  declare module.exports: $Exports<'msal/lib-es6/Constants'>;
}
declare module 'msal/lib-es6/ErrorMessage.js' {
  declare module.exports: $Exports<'msal/lib-es6/ErrorMessage'>;
}
declare module 'msal/lib-es6/IdToken.js' {
  declare module.exports: $Exports<'msal/lib-es6/IdToken'>;
}
declare module 'msal/lib-es6/index' {
  declare module.exports: $Exports<'msal/lib-es6'>;
}
declare module 'msal/lib-es6/index.js' {
  declare module.exports: $Exports<'msal/lib-es6'>;
}
declare module 'msal/lib-es6/ITenantDiscoveryResponse.js' {
  declare module.exports: $Exports<'msal/lib-es6/ITenantDiscoveryResponse'>;
}
declare module 'msal/lib-es6/IUri.js' {
  declare module.exports: $Exports<'msal/lib-es6/IUri'>;
}
declare module 'msal/lib-es6/Logger.js' {
  declare module.exports: $Exports<'msal/lib-es6/Logger'>;
}
declare module 'msal/lib-es6/RequestInfo.js' {
  declare module.exports: $Exports<'msal/lib-es6/RequestInfo'>;
}
declare module 'msal/lib-es6/Storage.js' {
  declare module.exports: $Exports<'msal/lib-es6/Storage'>;
}
declare module 'msal/lib-es6/User.js' {
  declare module.exports: $Exports<'msal/lib-es6/User'>;
}
declare module 'msal/lib-es6/UserAgentApplication.js' {
  declare module.exports: $Exports<'msal/lib-es6/UserAgentApplication'>;
}
declare module 'msal/lib-es6/Utils.js' {
  declare module.exports: $Exports<'msal/lib-es6/Utils'>;
}
declare module 'msal/lib-es6/XHRClient.js' {
  declare module.exports: $Exports<'msal/lib-es6/XHRClient'>;
}
declare module 'msal/webpack.config.js' {
  declare module.exports: $Exports<'msal/webpack.config'>;
}
