// flow-typed signature: a9aff8a12a8280eedec92c8f6e282672
// flow-typed version: <<STUB>>/pouchdb-adapter-idb_v^7.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pouchdb-adapter-idb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pouchdb-adapter-idb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pouchdb-adapter-idb/lib/index.es' {
  declare module.exports: any;
}

declare module 'pouchdb-adapter-idb/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pouchdb-adapter-idb/lib/index.es.js' {
  declare module.exports: $Exports<'pouchdb-adapter-idb/lib/index.es'>;
}
declare module 'pouchdb-adapter-idb/lib/index' {
  declare module.exports: $Exports<'pouchdb-adapter-idb/lib'>;
}
declare module 'pouchdb-adapter-idb/lib/index.js' {
  declare module.exports: $Exports<'pouchdb-adapter-idb/lib'>;
}
