// flow-typed signature: 4e8263ec62c201acc554153f4be1ee44
// flow-typed version: <<STUB>>/pouchdb-adapter-node-websql_v^7.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pouchdb-adapter-node-websql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pouchdb-adapter-node-websql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pouchdb-adapter-node-websql/lib/index.es' {
  declare module.exports: any;
}

declare module 'pouchdb-adapter-node-websql/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pouchdb-adapter-node-websql/lib/index.es.js' {
  declare module.exports: $Exports<'pouchdb-adapter-node-websql/lib/index.es'>;
}
declare module 'pouchdb-adapter-node-websql/lib/index' {
  declare module.exports: $Exports<'pouchdb-adapter-node-websql/lib'>;
}
declare module 'pouchdb-adapter-node-websql/lib/index.js' {
  declare module.exports: $Exports<'pouchdb-adapter-node-websql/lib'>;
}
