// flow-typed signature: 85c2b23683099aa1db6870e71bf4cc2a
// flow-typed version: <<STUB>>/react-rrule-generator_v^1.2.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-rrule-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-rrule-generator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-rrule-generator/build' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/config/env' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/config/jest/cssTransform' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/config/jest/fileTransform' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/config/paths' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/config/polyfills' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/config/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/config/webpack.config.prod.demo' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/config/webpack.config.prod' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/config/webpackDevServer.config' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/scripts/build-demo' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/scripts/build' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/scripts/start' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/scripts/test' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/demo/App' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/demo' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/End/After' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/End' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/End/OnDate' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/ReactRRuleGenerator' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Repeat/Daily' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Repeat/Hourly' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Repeat' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Repeat/Monthly' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Repeat/Monthly/On' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Repeat/Monthly/OnThe' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Repeat/Weekly' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Repeat/Yearly' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Repeat/Yearly/On' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Repeat/Yearly/OnThe' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Start' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/components/Start/OnDate' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/constants' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/translations/english' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/translations/german' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/translations' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeDailyInterval' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeEndAfter' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeEndMode' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeEndOnDate' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeFrequency' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeHourlyInterval' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyInterval' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyMode' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyOnDay' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyOnTheDay' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyOnTheWhich' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeRRule' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeStartOnDate' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeWeeklyDays' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeWeeklyInterval' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeWeekStartDay' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyMode' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnMonth' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnMonthday' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnTheMonth' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnTheMonthday' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnTheWhich' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeDaily' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeEnd' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeHourly' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeMonthly' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeMonthlyOn' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeMonthlyOnThe' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeOptions' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeRepeat' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeRRule' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeStart' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeWeekly' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeYearly' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeYearlyOn' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeYearlyOnThe' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/configureInitialState' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/numericalFieldHandler' {
  declare module.exports: any;
}

declare module 'react-rrule-generator/src/lib/utils/translateLabel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-rrule-generator/build/index' {
  declare module.exports: $Exports<'react-rrule-generator/build'>;
}
declare module 'react-rrule-generator/build/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/build'>;
}
declare module 'react-rrule-generator/config/env.js' {
  declare module.exports: $Exports<'react-rrule-generator/config/env'>;
}
declare module 'react-rrule-generator/config/jest/cssTransform.js' {
  declare module.exports: $Exports<'react-rrule-generator/config/jest/cssTransform'>;
}
declare module 'react-rrule-generator/config/jest/fileTransform.js' {
  declare module.exports: $Exports<'react-rrule-generator/config/jest/fileTransform'>;
}
declare module 'react-rrule-generator/config/paths.js' {
  declare module.exports: $Exports<'react-rrule-generator/config/paths'>;
}
declare module 'react-rrule-generator/config/polyfills.js' {
  declare module.exports: $Exports<'react-rrule-generator/config/polyfills'>;
}
declare module 'react-rrule-generator/config/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-rrule-generator/config/webpack.config.dev'>;
}
declare module 'react-rrule-generator/config/webpack.config.prod.demo.js' {
  declare module.exports: $Exports<'react-rrule-generator/config/webpack.config.prod.demo'>;
}
declare module 'react-rrule-generator/config/webpack.config.prod.js' {
  declare module.exports: $Exports<'react-rrule-generator/config/webpack.config.prod'>;
}
declare module 'react-rrule-generator/config/webpackDevServer.config.js' {
  declare module.exports: $Exports<'react-rrule-generator/config/webpackDevServer.config'>;
}
declare module 'react-rrule-generator/scripts/build-demo.js' {
  declare module.exports: $Exports<'react-rrule-generator/scripts/build-demo'>;
}
declare module 'react-rrule-generator/scripts/build.js' {
  declare module.exports: $Exports<'react-rrule-generator/scripts/build'>;
}
declare module 'react-rrule-generator/scripts/start.js' {
  declare module.exports: $Exports<'react-rrule-generator/scripts/start'>;
}
declare module 'react-rrule-generator/scripts/test.js' {
  declare module.exports: $Exports<'react-rrule-generator/scripts/test'>;
}
declare module 'react-rrule-generator/src/demo/App.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/demo/App'>;
}
declare module 'react-rrule-generator/src/demo/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/demo'>;
}
declare module 'react-rrule-generator/src/demo/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/demo'>;
}
declare module 'react-rrule-generator/src/lib/components/End/After.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/End/After'>;
}
declare module 'react-rrule-generator/src/lib/components/End/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/End'>;
}
declare module 'react-rrule-generator/src/lib/components/End/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/End'>;
}
declare module 'react-rrule-generator/src/lib/components/End/OnDate.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/End/OnDate'>;
}
declare module 'react-rrule-generator/src/lib/components/ReactRRuleGenerator.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/ReactRRuleGenerator'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Daily/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Daily'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Daily/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Daily'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Hourly/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Hourly'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Hourly/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Hourly'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Monthly/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Monthly'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Monthly/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Monthly'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Monthly/On.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Monthly/On'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Monthly/OnThe.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Monthly/OnThe'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Weekly/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Weekly'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Weekly/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Weekly'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Yearly/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Yearly'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Yearly/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Yearly'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Yearly/On.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Yearly/On'>;
}
declare module 'react-rrule-generator/src/lib/components/Repeat/Yearly/OnThe.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Repeat/Yearly/OnThe'>;
}
declare module 'react-rrule-generator/src/lib/components/Start/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Start'>;
}
declare module 'react-rrule-generator/src/lib/components/Start/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Start'>;
}
declare module 'react-rrule-generator/src/lib/components/Start/OnDate.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/components/Start/OnDate'>;
}
declare module 'react-rrule-generator/src/lib/constants/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/constants'>;
}
declare module 'react-rrule-generator/src/lib/constants/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/constants'>;
}
declare module 'react-rrule-generator/src/lib/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib'>;
}
declare module 'react-rrule-generator/src/lib/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib'>;
}
declare module 'react-rrule-generator/src/lib/translations/english.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/translations/english'>;
}
declare module 'react-rrule-generator/src/lib/translations/german.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/translations/german'>;
}
declare module 'react-rrule-generator/src/lib/translations/index' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/translations'>;
}
declare module 'react-rrule-generator/src/lib/translations/index.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/translations'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeDailyInterval.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeDailyInterval'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeEndAfter.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeEndAfter'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeEndMode.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeEndMode'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeEndOnDate.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeEndOnDate'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeFrequency.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeFrequency'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeHourlyInterval.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeHourlyInterval'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyInterval.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyInterval'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyMode.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyMode'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyOnDay.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyOnDay'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyOnTheDay.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyOnTheDay'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyOnTheWhich.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeMonthlyOnTheWhich'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeRRule.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeRRule'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeStartOnDate.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeStartOnDate'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeWeeklyDays.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeWeeklyDays'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeWeeklyInterval.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeWeeklyInterval'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeWeekStartDay.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeWeekStartDay'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyMode.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyMode'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnMonth.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnMonth'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnMonthday.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnMonthday'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnTheMonth.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnTheMonth'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnTheMonthday.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnTheMonthday'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnTheWhich.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/fromString/computeYearlyOnTheWhich'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeDaily.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeDaily'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeEnd.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeEnd'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeHourly.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeHourly'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeMonthly.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeMonthly'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeMonthlyOn.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeMonthlyOn'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeMonthlyOnThe.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeMonthlyOnThe'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeOptions.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeOptions'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeRepeat.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeRepeat'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeRRule.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeRRule'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeStart.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeStart'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeWeekly.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeWeekly'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeYearly.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeYearly'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeYearlyOn.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeYearlyOn'>;
}
declare module 'react-rrule-generator/src/lib/utils/computeRRule/toString/computeYearlyOnThe.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/computeRRule/toString/computeYearlyOnThe'>;
}
declare module 'react-rrule-generator/src/lib/utils/configureInitialState.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/configureInitialState'>;
}
declare module 'react-rrule-generator/src/lib/utils/numericalFieldHandler.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/numericalFieldHandler'>;
}
declare module 'react-rrule-generator/src/lib/utils/translateLabel.js' {
  declare module.exports: $Exports<'react-rrule-generator/src/lib/utils/translateLabel'>;
}
