// flow-typed signature: 9aaa71cd5dc8cdc2b00a6590f306a3e9
// flow-typed version: <<STUB>>/rxdb_v^8.0.4/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rxdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rxdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rxdb/dist/es/browserify.index' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/change-event-buffer' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/core' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/crypter' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/data-migrator' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/doc-cache' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/hooks' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/mquery/mquery_utils' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/mquery/mquery' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/overwritable' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugin' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/adapter-check' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/ajv-validate' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/attachments' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/encryption' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/error-messages' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/in-memory' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/json-dump' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/key-compression' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/leader-election' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/local-documents' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/no-validate' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/replication-graphql/crawling-checkpoint' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/replication-graphql/helper' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/replication-graphql' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/replication' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/schema-check' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/server' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/update' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/validate-z-schema' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/validate' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/plugins/watch-for-changes' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/pouch-db' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/query-cache' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/query-change-detector' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/rx-change-event' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/rx-collection-helper' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/rx-collection' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/rx-database' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/rx-document-prototype-merge' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/rx-document' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/rx-error' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/rx-query' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/rx-schema' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/modules/clone.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/modules/crypto-js.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/modules/deep-equal.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/modules/graphql-client.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/modules/mocha.parallel.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/modules/modifiyjs.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/modules/object-path.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/modules/pouchdb-replication.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/modules/pouchdb-selector-core.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/modules/random-token.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/plugins/replication-graphql' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/plugins/replication' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/pouch' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/rx-attachment' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/rx-change-event' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/rx-collection' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/rx-database' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/rx-document' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/rx-error' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/rx-plugin' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/rx-query' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/types/rx-schema' {
  declare module.exports: any;
}

declare module 'rxdb/dist/es/util' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/browserify.index' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/change-event-buffer' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/core' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/crypter' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/data-migrator' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/doc-cache' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/hooks' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/mquery/mquery_utils' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/mquery/mquery' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/overwritable' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugin' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/adapter-check' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/ajv-validate' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/attachments' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/encryption' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/error-messages' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/in-memory' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/json-dump' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/key-compression' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/leader-election' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/local-documents' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/no-validate' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/replication-graphql/crawling-checkpoint' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/replication-graphql/helper' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/replication-graphql' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/replication' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/schema-check' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/server' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/update' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/validate-z-schema' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/validate' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/plugins/watch-for-changes' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/pouch-db' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/query-cache' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/query-change-detector' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/rx-change-event' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/rx-collection-helper' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/rx-collection' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/rx-database' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/rx-document-prototype-merge' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/rx-document' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/rx-error' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/rx-query' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/rx-schema' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/modules/clone.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/modules/crypto-js.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/modules/deep-equal.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/modules/graphql-client.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/modules/mocha.parallel.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/modules/modifiyjs.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/modules/object-path.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/modules/pouchdb-replication.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/modules/pouchdb-selector-core.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/modules/random-token.d' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/plugins/replication-graphql' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/plugins/replication' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/pouch' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/rx-attachment' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/rx-change-event' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/rx-collection' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/rx-database' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/rx-document' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/rx-error' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/rx-plugin' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/rx-query' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/types/rx-schema' {
  declare module.exports: any;
}

declare module 'rxdb/dist/lib/util' {
  declare module.exports: any;
}

declare module 'rxdb/dist/rxdb.browserify' {
  declare module.exports: any;
}

declare module 'rxdb/dist/rxdb.browserify.min' {
  declare module.exports: any;
}

declare module 'rxdb/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'rxdb/scripts/profile' {
  declare module.exports: any;
}

declare module 'rxdb/scripts/transpile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rxdb/dist/es/browserify.index.js' {
  declare module.exports: $Exports<'rxdb/dist/es/browserify.index'>;
}
declare module 'rxdb/dist/es/change-event-buffer.js' {
  declare module.exports: $Exports<'rxdb/dist/es/change-event-buffer'>;
}
declare module 'rxdb/dist/es/core.js' {
  declare module.exports: $Exports<'rxdb/dist/es/core'>;
}
declare module 'rxdb/dist/es/crypter.js' {
  declare module.exports: $Exports<'rxdb/dist/es/crypter'>;
}
declare module 'rxdb/dist/es/data-migrator.js' {
  declare module.exports: $Exports<'rxdb/dist/es/data-migrator'>;
}
declare module 'rxdb/dist/es/doc-cache.js' {
  declare module.exports: $Exports<'rxdb/dist/es/doc-cache'>;
}
declare module 'rxdb/dist/es/hooks.js' {
  declare module.exports: $Exports<'rxdb/dist/es/hooks'>;
}
declare module 'rxdb/dist/es/index' {
  declare module.exports: $Exports<'rxdb/dist/es'>;
}
declare module 'rxdb/dist/es/index.js' {
  declare module.exports: $Exports<'rxdb/dist/es'>;
}
declare module 'rxdb/dist/es/mquery/mquery_utils.js' {
  declare module.exports: $Exports<'rxdb/dist/es/mquery/mquery_utils'>;
}
declare module 'rxdb/dist/es/mquery/mquery.js' {
  declare module.exports: $Exports<'rxdb/dist/es/mquery/mquery'>;
}
declare module 'rxdb/dist/es/overwritable.js' {
  declare module.exports: $Exports<'rxdb/dist/es/overwritable'>;
}
declare module 'rxdb/dist/es/plugin.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugin'>;
}
declare module 'rxdb/dist/es/plugins/adapter-check.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/adapter-check'>;
}
declare module 'rxdb/dist/es/plugins/ajv-validate.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/ajv-validate'>;
}
declare module 'rxdb/dist/es/plugins/attachments.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/attachments'>;
}
declare module 'rxdb/dist/es/plugins/encryption.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/encryption'>;
}
declare module 'rxdb/dist/es/plugins/error-messages.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/error-messages'>;
}
declare module 'rxdb/dist/es/plugins/in-memory.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/in-memory'>;
}
declare module 'rxdb/dist/es/plugins/json-dump.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/json-dump'>;
}
declare module 'rxdb/dist/es/plugins/key-compression.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/key-compression'>;
}
declare module 'rxdb/dist/es/plugins/leader-election.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/leader-election'>;
}
declare module 'rxdb/dist/es/plugins/local-documents.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/local-documents'>;
}
declare module 'rxdb/dist/es/plugins/no-validate.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/no-validate'>;
}
declare module 'rxdb/dist/es/plugins/replication-graphql/crawling-checkpoint.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/replication-graphql/crawling-checkpoint'>;
}
declare module 'rxdb/dist/es/plugins/replication-graphql/helper.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/replication-graphql/helper'>;
}
declare module 'rxdb/dist/es/plugins/replication-graphql/index' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/replication-graphql'>;
}
declare module 'rxdb/dist/es/plugins/replication-graphql/index.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/replication-graphql'>;
}
declare module 'rxdb/dist/es/plugins/replication.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/replication'>;
}
declare module 'rxdb/dist/es/plugins/schema-check.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/schema-check'>;
}
declare module 'rxdb/dist/es/plugins/server.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/server'>;
}
declare module 'rxdb/dist/es/plugins/update.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/update'>;
}
declare module 'rxdb/dist/es/plugins/validate-z-schema.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/validate-z-schema'>;
}
declare module 'rxdb/dist/es/plugins/validate.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/validate'>;
}
declare module 'rxdb/dist/es/plugins/watch-for-changes.js' {
  declare module.exports: $Exports<'rxdb/dist/es/plugins/watch-for-changes'>;
}
declare module 'rxdb/dist/es/pouch-db.js' {
  declare module.exports: $Exports<'rxdb/dist/es/pouch-db'>;
}
declare module 'rxdb/dist/es/query-cache.js' {
  declare module.exports: $Exports<'rxdb/dist/es/query-cache'>;
}
declare module 'rxdb/dist/es/query-change-detector.js' {
  declare module.exports: $Exports<'rxdb/dist/es/query-change-detector'>;
}
declare module 'rxdb/dist/es/rx-change-event.js' {
  declare module.exports: $Exports<'rxdb/dist/es/rx-change-event'>;
}
declare module 'rxdb/dist/es/rx-collection-helper.js' {
  declare module.exports: $Exports<'rxdb/dist/es/rx-collection-helper'>;
}
declare module 'rxdb/dist/es/rx-collection.js' {
  declare module.exports: $Exports<'rxdb/dist/es/rx-collection'>;
}
declare module 'rxdb/dist/es/rx-database.js' {
  declare module.exports: $Exports<'rxdb/dist/es/rx-database'>;
}
declare module 'rxdb/dist/es/rx-document-prototype-merge.js' {
  declare module.exports: $Exports<'rxdb/dist/es/rx-document-prototype-merge'>;
}
declare module 'rxdb/dist/es/rx-document.js' {
  declare module.exports: $Exports<'rxdb/dist/es/rx-document'>;
}
declare module 'rxdb/dist/es/rx-error.js' {
  declare module.exports: $Exports<'rxdb/dist/es/rx-error'>;
}
declare module 'rxdb/dist/es/rx-query.js' {
  declare module.exports: $Exports<'rxdb/dist/es/rx-query'>;
}
declare module 'rxdb/dist/es/rx-schema.js' {
  declare module.exports: $Exports<'rxdb/dist/es/rx-schema'>;
}
declare module 'rxdb/dist/es/types/index' {
  declare module.exports: $Exports<'rxdb/dist/es/types'>;
}
declare module 'rxdb/dist/es/types/index.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types'>;
}
declare module 'rxdb/dist/es/types/modules/clone.d.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/modules/clone.d'>;
}
declare module 'rxdb/dist/es/types/modules/crypto-js.d.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/modules/crypto-js.d'>;
}
declare module 'rxdb/dist/es/types/modules/deep-equal.d.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/modules/deep-equal.d'>;
}
declare module 'rxdb/dist/es/types/modules/graphql-client.d.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/modules/graphql-client.d'>;
}
declare module 'rxdb/dist/es/types/modules/mocha.parallel.d.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/modules/mocha.parallel.d'>;
}
declare module 'rxdb/dist/es/types/modules/modifiyjs.d.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/modules/modifiyjs.d'>;
}
declare module 'rxdb/dist/es/types/modules/object-path.d.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/modules/object-path.d'>;
}
declare module 'rxdb/dist/es/types/modules/pouchdb-replication.d.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/modules/pouchdb-replication.d'>;
}
declare module 'rxdb/dist/es/types/modules/pouchdb-selector-core.d.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/modules/pouchdb-selector-core.d'>;
}
declare module 'rxdb/dist/es/types/modules/random-token.d.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/modules/random-token.d'>;
}
declare module 'rxdb/dist/es/types/plugins/replication-graphql.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/plugins/replication-graphql'>;
}
declare module 'rxdb/dist/es/types/plugins/replication.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/plugins/replication'>;
}
declare module 'rxdb/dist/es/types/pouch.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/pouch'>;
}
declare module 'rxdb/dist/es/types/rx-attachment.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/rx-attachment'>;
}
declare module 'rxdb/dist/es/types/rx-change-event.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/rx-change-event'>;
}
declare module 'rxdb/dist/es/types/rx-collection.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/rx-collection'>;
}
declare module 'rxdb/dist/es/types/rx-database.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/rx-database'>;
}
declare module 'rxdb/dist/es/types/rx-document.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/rx-document'>;
}
declare module 'rxdb/dist/es/types/rx-error.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/rx-error'>;
}
declare module 'rxdb/dist/es/types/rx-plugin.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/rx-plugin'>;
}
declare module 'rxdb/dist/es/types/rx-query.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/rx-query'>;
}
declare module 'rxdb/dist/es/types/rx-schema.js' {
  declare module.exports: $Exports<'rxdb/dist/es/types/rx-schema'>;
}
declare module 'rxdb/dist/es/util.js' {
  declare module.exports: $Exports<'rxdb/dist/es/util'>;
}
declare module 'rxdb/dist/lib/browserify.index.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/browserify.index'>;
}
declare module 'rxdb/dist/lib/change-event-buffer.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/change-event-buffer'>;
}
declare module 'rxdb/dist/lib/core.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/core'>;
}
declare module 'rxdb/dist/lib/crypter.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/crypter'>;
}
declare module 'rxdb/dist/lib/data-migrator.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/data-migrator'>;
}
declare module 'rxdb/dist/lib/doc-cache.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/doc-cache'>;
}
declare module 'rxdb/dist/lib/hooks.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/hooks'>;
}
declare module 'rxdb/dist/lib/index' {
  declare module.exports: $Exports<'rxdb/dist/lib'>;
}
declare module 'rxdb/dist/lib/index.js' {
  declare module.exports: $Exports<'rxdb/dist/lib'>;
}
declare module 'rxdb/dist/lib/mquery/mquery_utils.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/mquery/mquery_utils'>;
}
declare module 'rxdb/dist/lib/mquery/mquery.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/mquery/mquery'>;
}
declare module 'rxdb/dist/lib/overwritable.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/overwritable'>;
}
declare module 'rxdb/dist/lib/plugin.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugin'>;
}
declare module 'rxdb/dist/lib/plugins/adapter-check.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/adapter-check'>;
}
declare module 'rxdb/dist/lib/plugins/ajv-validate.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/ajv-validate'>;
}
declare module 'rxdb/dist/lib/plugins/attachments.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/attachments'>;
}
declare module 'rxdb/dist/lib/plugins/encryption.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/encryption'>;
}
declare module 'rxdb/dist/lib/plugins/error-messages.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/error-messages'>;
}
declare module 'rxdb/dist/lib/plugins/in-memory.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/in-memory'>;
}
declare module 'rxdb/dist/lib/plugins/json-dump.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/json-dump'>;
}
declare module 'rxdb/dist/lib/plugins/key-compression.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/key-compression'>;
}
declare module 'rxdb/dist/lib/plugins/leader-election.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/leader-election'>;
}
declare module 'rxdb/dist/lib/plugins/local-documents.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/local-documents'>;
}
declare module 'rxdb/dist/lib/plugins/no-validate.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/no-validate'>;
}
declare module 'rxdb/dist/lib/plugins/replication-graphql/crawling-checkpoint.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/replication-graphql/crawling-checkpoint'>;
}
declare module 'rxdb/dist/lib/plugins/replication-graphql/helper.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/replication-graphql/helper'>;
}
declare module 'rxdb/dist/lib/plugins/replication-graphql/index' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/replication-graphql'>;
}
declare module 'rxdb/dist/lib/plugins/replication-graphql/index.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/replication-graphql'>;
}
declare module 'rxdb/dist/lib/plugins/replication.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/replication'>;
}
declare module 'rxdb/dist/lib/plugins/schema-check.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/schema-check'>;
}
declare module 'rxdb/dist/lib/plugins/server.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/server'>;
}
declare module 'rxdb/dist/lib/plugins/update.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/update'>;
}
declare module 'rxdb/dist/lib/plugins/validate-z-schema.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/validate-z-schema'>;
}
declare module 'rxdb/dist/lib/plugins/validate.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/validate'>;
}
declare module 'rxdb/dist/lib/plugins/watch-for-changes.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/plugins/watch-for-changes'>;
}
declare module 'rxdb/dist/lib/pouch-db.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/pouch-db'>;
}
declare module 'rxdb/dist/lib/query-cache.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/query-cache'>;
}
declare module 'rxdb/dist/lib/query-change-detector.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/query-change-detector'>;
}
declare module 'rxdb/dist/lib/rx-change-event.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/rx-change-event'>;
}
declare module 'rxdb/dist/lib/rx-collection-helper.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/rx-collection-helper'>;
}
declare module 'rxdb/dist/lib/rx-collection.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/rx-collection'>;
}
declare module 'rxdb/dist/lib/rx-database.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/rx-database'>;
}
declare module 'rxdb/dist/lib/rx-document-prototype-merge.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/rx-document-prototype-merge'>;
}
declare module 'rxdb/dist/lib/rx-document.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/rx-document'>;
}
declare module 'rxdb/dist/lib/rx-error.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/rx-error'>;
}
declare module 'rxdb/dist/lib/rx-query.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/rx-query'>;
}
declare module 'rxdb/dist/lib/rx-schema.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/rx-schema'>;
}
declare module 'rxdb/dist/lib/types/index' {
  declare module.exports: $Exports<'rxdb/dist/lib/types'>;
}
declare module 'rxdb/dist/lib/types/index.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types'>;
}
declare module 'rxdb/dist/lib/types/modules/clone.d.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/modules/clone.d'>;
}
declare module 'rxdb/dist/lib/types/modules/crypto-js.d.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/modules/crypto-js.d'>;
}
declare module 'rxdb/dist/lib/types/modules/deep-equal.d.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/modules/deep-equal.d'>;
}
declare module 'rxdb/dist/lib/types/modules/graphql-client.d.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/modules/graphql-client.d'>;
}
declare module 'rxdb/dist/lib/types/modules/mocha.parallel.d.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/modules/mocha.parallel.d'>;
}
declare module 'rxdb/dist/lib/types/modules/modifiyjs.d.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/modules/modifiyjs.d'>;
}
declare module 'rxdb/dist/lib/types/modules/object-path.d.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/modules/object-path.d'>;
}
declare module 'rxdb/dist/lib/types/modules/pouchdb-replication.d.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/modules/pouchdb-replication.d'>;
}
declare module 'rxdb/dist/lib/types/modules/pouchdb-selector-core.d.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/modules/pouchdb-selector-core.d'>;
}
declare module 'rxdb/dist/lib/types/modules/random-token.d.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/modules/random-token.d'>;
}
declare module 'rxdb/dist/lib/types/plugins/replication-graphql.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/plugins/replication-graphql'>;
}
declare module 'rxdb/dist/lib/types/plugins/replication.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/plugins/replication'>;
}
declare module 'rxdb/dist/lib/types/pouch.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/pouch'>;
}
declare module 'rxdb/dist/lib/types/rx-attachment.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/rx-attachment'>;
}
declare module 'rxdb/dist/lib/types/rx-change-event.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/rx-change-event'>;
}
declare module 'rxdb/dist/lib/types/rx-collection.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/rx-collection'>;
}
declare module 'rxdb/dist/lib/types/rx-database.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/rx-database'>;
}
declare module 'rxdb/dist/lib/types/rx-document.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/rx-document'>;
}
declare module 'rxdb/dist/lib/types/rx-error.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/rx-error'>;
}
declare module 'rxdb/dist/lib/types/rx-plugin.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/rx-plugin'>;
}
declare module 'rxdb/dist/lib/types/rx-query.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/rx-query'>;
}
declare module 'rxdb/dist/lib/types/rx-schema.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/types/rx-schema'>;
}
declare module 'rxdb/dist/lib/util.js' {
  declare module.exports: $Exports<'rxdb/dist/lib/util'>;
}
declare module 'rxdb/dist/rxdb.browserify.js' {
  declare module.exports: $Exports<'rxdb/dist/rxdb.browserify'>;
}
declare module 'rxdb/dist/rxdb.browserify.min.js' {
  declare module.exports: $Exports<'rxdb/dist/rxdb.browserify.min'>;
}
declare module 'rxdb/scripts/postinstall.js' {
  declare module.exports: $Exports<'rxdb/scripts/postinstall'>;
}
declare module 'rxdb/scripts/profile.js' {
  declare module.exports: $Exports<'rxdb/scripts/profile'>;
}
declare module 'rxdb/scripts/transpile.js' {
  declare module.exports: $Exports<'rxdb/scripts/transpile'>;
}
