#!/bin/zsh

function lintit () {
  OUTPUT=$(git diff --cached --name-only | grep -E '(.js|.jsx|.es6)$')
  a=("${(f)OUTPUT}")
  eslint $a
  if [ $? -ne 0 ]; then
    echo "ERROR: Check eslint hints."
    exit 1 # reject
  fi
}
lintit
