#!/bin/zsh

function lintIt () {
  OUTPUT=$(git diff --cached --name-status | grep -E '(.js|.jsx|.es6)$' | grep -E '^(A|M)' | awk '{print $2}')
  if [ ${#OUTPUT} -lt 1 ]; then
    echo "No JS related file in commit, eslint check skipped"
    exit 0
  fi
  a=("${(f)OUTPUT}")
  eslint $a
  if [ $? -ne 0 ]; then
    echo "ERROR: Check eslint hints."
    exit 1 # reject
  fi
}
lintIt
