// #region Exchange
export const GET_EXCHANGE_EVENTS_BEGIN = 'GET_EXCHANGE_EVENTS_BEGIN';
export const GET_EXCHANGE_EVENTS_SUCCESS = 'GET_EXCHANGE_EVENTS_SUCCESS';
export const GET_EXCHANGE_EVENTS_FAILURE = 'GET_EXCHANGE_EVENTS_FAILURE';

export const CREATE_EXCHANGE_EVENTS_BEGIN = 'CREATE_EXCHANGE_EVENTS_BEGIN';
export const CREATE_EXCHANGE_EVENTS_SUCCESS = 'CREATE_EXCHANGE_EVENTS_SUCCESS';
export const CREATE_EXCHANGE_EVENTS_FAILURE = 'CREATE_EXCHANGE_EVENTS_FAILURE';

export const EDIT_EXCHANGE_SINGLE_EVENT_BEGIN = 'EDIT_EXCHANGE_SINGLE_EVENT_BEGIN';
export const EDIT_EXCHANGE_SINGLE_EVENT_SUCCESS = 'EDIT_EXCHANGE_SINGLE_EVENT_SUCCESS';
export const EDIT_EXCHANGE_SINGLE_EVENT_FAILURE = 'EDIT_EXCHANGE_SINGLE_EVENT_FAILURE';

export const EDIT_EXCHANGE_FUTURE_EVENT_BEGIN = 'EDIT_EXCHANGE_FUTURE_EVENT_BEGIN';
export const EDIT_EXCHANGE_FUTURE_EVENT_SUCCESS = 'EDIT_EXCHANGE_FUTURE_EVENT_SUCCESS';
export const EDIT_EXCHANGE_FUTURE_EVENT_FAILURE = 'EDIT_EXCHANGE_FUTURE_EVENT_FAILURE';

export const EDIT_EXCHANGE_ALL_EVENT_BEGIN = 'EDIT_EXCHANGE_ALL_EVENT_BEGIN';
export const EDIT_EXCHANGE_ALL_EVENT_SUCCESS = 'EDIT_EXCHANGE_ALL_EVENT_SUCCESS';
export const EDIT_EXCHANGE_ALL_EVENT_FAILURE = 'EDIT_EXCHANGE_ALL_EVENT_FAILURE';

export const DELETE_EXCHANGE_SINGLE_EVENT_BEGIN = 'DELETE_EXCHANGE_SINGLE_EVENT_BEGIN';
export const DELETE_EXCHANGE_SINGLE_EVENT_SUCCESS = 'DELETE_EXCHANGE_SINGLE_EVENT_SUCCESS';
export const DELETE_EXCHANGE_SINGLE_EVENT_FAILURE = 'DELETE_EXCHANGE_SINGLE_EVENT_FAILURE';

export const DELETE_EXCHANGE_FUTURE_EVENT_BEGIN = 'DELETE_EXCHANGE_FUTURE_EVENT_BEGIN';
export const DELETE_EXCHANGE_FUTURE_EVENT_SUCCESS = 'DELETE_EXCHANGE_FUTURE_EVENT_SUCCESS';
export const DELETE_EXCHANGE_FUTURE_EVENT_FAILURE = 'DELETE_EXCHANGE_FUTURE_EVENT_FAILURE';

export const DELETE_EXCHANGE_ALL_EVENT_BEGIN = 'DELETE_EXCHANGE_ALL_EVENT_BEGIN';
export const DELETE_EXCHANGE_ALL_EVENT_SUCCESS = 'DELETE_EXCHANGE_ALL_EVENT_SUCCESS';
export const DELETE_EXCHANGE_ALL_EVENT_FAILURE = 'DELETE_EXCHANGE_ALL_EVENT_FAILURE';

export const beginGetExchangeEvents = (resp) => ({
  type: GET_EXCHANGE_EVENTS_BEGIN,
  payload: resp
});

export const getExchangeEventsSuccess = (resp) => ({
  type: GET_EXCHANGE_EVENTS_SUCCESS,
  payload: resp
});

export const createEwsEventBegin = (resp) => ({
  type: CREATE_EXCHANGE_EVENTS_BEGIN,
  payload: resp
});

export const editEwsSingleEventBegin = (resp) => ({
  type: EDIT_EXCHANGE_SINGLE_EVENT_BEGIN,
  payload: resp
});

export const editEwsFutureEventBegin = (resp) => ({
  type: EDIT_EXCHANGE_FUTURE_EVENT_BEGIN,
  payload: resp
});

export const editEwsAllEventBegin = (resp) => ({
  type: EDIT_EXCHANGE_ALL_EVENT_BEGIN,
  payload: resp
});

export const deleteEwsSingleEventBegin = (resp) => ({
  type: DELETE_EXCHANGE_SINGLE_EVENT_BEGIN,
  payload: resp
});

export const deleteEwsAllEventBegin = (resp) => ({
  type: DELETE_EXCHANGE_ALL_EVENT_BEGIN,
  payload: resp
});

export const deleteEwsFutureEventBegin = (resp) => ({
  type: DELETE_EXCHANGE_FUTURE_EVENT_BEGIN,
  payload: resp
});
// #endregion
