// #region GOOGLE
export const GET_GOOGLE_EVENTS_BEGIN = 'GET_GOOGLE_EVENTS_BEGIN';
export const GET_GOOGLE_EVENTS_SUCCESS = 'GET_GOOGLE_EVENTS_SUCCESS';
export const GET_GOOGLE_EVENTS_FAILURE = 'GET_GOOGLE_EVENTS_FAILURE';

export const CREATE_GOOGLE_EVENTS_BEGIN = 'CREATE_GOOGLE_EVENTS_BEGIN';
export const CREATE_GOOGLE_EVENTS_SUCCESS = 'CREATE_GOOGLE_EVENTS_SUCCESS';
export const CREATE_GOOGLE_EVENTS_FAILURE = 'CREATE_GOOGLE_EVENTS_FAILURE';

export const EDIT_GOOGLE_SINGLE_EVENT_BEGIN = 'EDIT_GOOGLE_SINGLE_EVENT_BEGIN';
export const EDIT_GOOGLE_SINGLE_EVENT_SUCCESS = 'EDIT_GOOGLE_SINGLE_EVENT_SUCCESS';
export const EDIT_GOOGLE_SINGLE_EVENT_FAILURE = 'EDIT_GOOGLE_SINGLE_EVENT_FAILURE';

export const EDIT_GOOGLE_FUTURE_EVENT_BEGIN = 'EDIT_GOOGLE_FUTURE_EVENT_BEGIN';
export const EDIT_GOOGLE_FUTURE_EVENT_SUCCESS = 'EDIT_GOOGLE_FUTURE_EVENT_SUCCESS';
export const EDIT_GOOGLE_FUTURE_EVENT_FAILURE = 'EDIT_GOOGLE_FUTURE_EVENT_FAILURE';

export const EDIT_GOOGLE_ALL_EVENT_BEGIN = 'EDIT_GOOGLE_ALL_EVENT_BEGIN';
export const EDIT_GOOGLE_ALL_EVENT_SUCCESS = 'EDIT_GOOGLE_ALL_EVENT_SUCCESS';
export const EDIT_GOOGLE_ALL_EVENT_FAILURE = 'EDIT_GOOGLE_ALL_EVENT_FAILURE';

export const DELETE_GOOGLE_SINGLE_EVENT_BEGIN = 'DELETE_GOOGLE_SINGLE_EVENT_BEGIN';
export const DELETE_GOOGLE_SINGLE_EVENT_SUCCESS = 'DELETE_GOOGLE_SINGLE_EVENT_SUCCESS';
export const DELETE_GOOGLE_SINGLE_EVENT_FAILURE = 'DELETE_GOOGLE_SINGLE_EVENT_FAILURE';

export const DELETE_GOOGLE_FUTURE_EVENT_BEGIN = 'DELETE_GOOGLE_FUTURE_EVENT_BEGIN';
export const DELETE_GOOGLE_FUTURE_EVENT_SUCCESS = 'DELETE_GOOGLE_FUTURE_EVENT_SUCCESS';
export const DELETE_GOOGLE_FUTURE_EVENT_FAILURE = 'DELETE_GOOGLE_FUTURE_EVENT_FAILURE';

export const DELETE_GOOGLE_ALL_EVENT_BEGIN = 'DELETE_GOOGLE_ALL_EVENT_BEGIN';
export const DELETE_GOOGLE_ALL_EVENT_SUCCESS = 'DELETE_GOOGLE_ALL_EVENT_SUCCESS';
export const DELETE_GOOGLE_ALL_EVENT_FAILURE = 'DELETE_GOOGLE_ALL_EVENT_FAILURE';

export const beginGetGoogleEvents = (resp) => ({
  type: GET_GOOGLE_EVENTS_BEGIN,
  payload: resp
});

export const createGoogleEventBegin = (resp) => ({
  type: CREATE_GOOGLE_EVENTS_BEGIN,
  payload: resp
});
export const editGoogleSingleEventBegin = (resp) => ({
  type: EDIT_GOOGLE_SINGLE_EVENT_BEGIN,
  payload: resp
});

export const editGoogleFutureEventBegin = (resp) => ({
  type: EDIT_GOOGLE_FUTURE_EVENT_BEGIN,
  payload: resp
});

export const editGoogleAllEventBegin = (resp) => ({
  type: EDIT_GOOGLE_ALL_EVENT_BEGIN,
  payload: resp
});

export const deleteGoogleSingleEventBegin = (resp) => ({
  type: DELETE_GOOGLE_SINGLE_EVENT_BEGIN,
  payload: resp
});

export const deleteGoogleAllEventBegin = (resp) => ({
  type: DELETE_GOOGLE_ALL_EVENT_BEGIN,
  payload: resp
});

export const deleteGoogleFutureEventBegin = (resp) => ({
  type: DELETE_GOOGLE_FUTURE_EVENT_BEGIN,
  payload: resp
});
// #endregion
