#!/bin/sh
if [ "$#" -ne 2 ]; then
    logger "EdisonMail: need to set pid and process name"
    exit 1
fi
pidValue=$1
processName=$2
echo $pidValue | grep "[^0-9]" > /dev/null 2>&1

if [ "$?" -eq "0" ]; then
  logger "EdisonMail: pid value is not a number - $pidValue"
  exit 2
fi

if [ $pidValue -lt 1 ]; then
    logger "EdisonMail: pid value incorrect"
    exit 2
fi
logger "EdisonMail: monitoring pid $pidValue"
sleep 5
ps -p $pidValue -o command= | grep "$processName" > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
    logger "EdisonMail: $processName for pid $pidValue still running, killing it now"
    kill -9 $pidValue
fi
logger "EdisonMail: $processName for pid $pidValue have died"
exit 0


