export const ICLOUD_ACCOUNT = 'ICLOUD_ACCOUNT';
export const ICLOUD_URL = 'https://caldav.icloud.com/';

export const CALDAV_PROVIDER = 'CALDAV_PROVIDER';

export const DELETE_SINGLE_EVENT = 'DELETE_SINGLE_EVENT';
export const DELETE_ALL_RECURRING_EVENTS = 'DELETE_ALL_RECURRING EVENTS';
export const DELETE_FUTURE_RECCURRING_EVENTS = 'DELETE_FUTURE_RECURRING_EVENTS';
export const DELETE_NON_MASTER_EVENTS = 'DELETE_NON_MASTER_EVENTS';

export const UPDATE_ICALSTRING = 'UPDATE_ICALSTRING';
export const UPDATE_SINGLE_EVENT = 'UPDATE_SINGLE_EVENT';
export const UPDATE_ALL_RECURRING_EVENTS = 'UPDATE_ALL_RECCURING_EVENTS';
export const UPDATE_FUTURE_RECURRING_EVENTS = 'UPDATE_FUTURE_RECURRING_EVENTS';
export const UPDATE_MASTER_EVENT = 'UPDATE_MASTER_EVENT';

export const UPSERT_RECURRENCE_PATTERN = 'UPSERT_RECURRENCE_PATTERN';
export const UPDATE_RECURRENCE_PATTERN = 'UPDATE_RECURRENCE_PATTERN';

export const GET_MASTER_EVENT = 'GET_MASTER_EVENT';
export const GET_ALL_EVENT = 'GET_ALL_EVENT';

export const DELETE_EDITED_EVENT = 'DELETE_EDITED_EVENT';
export const DELETE_NON_EDITED_EVENT = 'DELETE_NON_EDITED_EVENT';